apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-shop-tls
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: tls-secret

  # At least one of a DNS Name, URI, IP address or otherName is required.
  dnsNames:
    - segunagoro.com
    - www.segunagoro.com
  
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer

  # keystores allows adding additional output formats. This is an example for reference only.
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: example-com-tls-keystore
        key: password
      profile: Modern2023