---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-alerts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  project: default
  source:
    repoURL: https://github.com/example/repo.git
    targetRevision: master
    path: ./socks-shop-eks-deployment/deploy/kubernetes/manifests-alerting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
