---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-ssl
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager 
  project: default
  source:
    repoURL: https://github.com/Gunda-Lo/sock-shop-cicd.git
    targetRevision: master
    path: ./socks-shop-eks-deployment/deploy/kubernetes/ingress/letsEncrypt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
