---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop 
  project: default
  source:
    repoURL: https://github.com/Gunda-Lo/sock-shop-cicd.git
    targetRevision: main 
    path: ./socks-shop-eks-deployment/deploy/kubernetes/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
